name: release-pr

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-pr
  cancel-in-progress: true

jobs:
  release_pr:
    name: Prepare Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: release-plz / release-pr
        id: release-pr
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
