name: release

on:
  push:
    branches: [ main ]
    paths:
      - Cargo.toml
      - CHANGELOG.md

permissions:
  contents: write

jobs:
  release:
    name: Publish crates and GitHub tag/release
    runs-on: ubuntu-latest
    if: >
      startsWith(github.event.head_commit.message, 'chore: release v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: release-plz / release
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
